### ISSUE TITLE
Question regarding SNMP handler creation

### ISSUE THREAD

**Issue by vaxx** [ehazlett/sensu-py#1]
Hi Evan,

I am having some difficulty implementing a snmp handler using sensu-py. The snmp portion is working as intended, however the script fails once the Handler class is implemented. Admittedly I am a bit lost at this point and would appreciate any guidance. The handler throws the following error:

Traceback (most recent call last):
  File "wtf.py", line 151, in <module>
    m = SNMPHandler()
  File "/usr/local/lib/python2.7/dist-packages/sensu/handler.py", line 31, in **init**
    self.settings = utils.load_settings()
  File "/usr/local/lib/python2.7/dist-packages/sensu/utils.py", line 73, in load_settings
    data = dict(data.items() + load_config(cfg).items())
  File "/usr/local/lib/python2.7/dist-packages/sensu/utils.py", line 68, in load_config
    return json.loads(open(filename, 'r').read())
  File "/usr/lib/python2.7/dist-packages/simplejson/**init**.py", line 413, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 405, in decode
    raise JSONDecodeError("Extra data", s, end, len(s))
simplejson.decoder.JSONDecodeError: Extra data: line 21 column 1 - line 22 column 1 (char 407 - 409)

If you have any ideas that would be wonderful. I will be glad to sanitize the snmp handler fully and open a pull request once debugging is complete.

Thanks,

Brian

**Comment by ehazlett** [comment]
Can you post the output of "utils.load_settings()" -- it looks like that contains invalid JSON.

**Comment by vaxx** [comment]
Unfortunately I cannot sanitize that data as there is quite a bit of it. I will run it through a linter and report back any findings. Thanks Evan.
